kind: pipeline
name: web-build-master

steps:
  - name: build-and-deploy
    image: debian:buster-slim
    commands:
      - apt-get update
      - apt-get install -y wget make git
      - wget -O "./hugo.deb" "https://github.com/gohugoio/hugo/releases/download/v0.63.1/hugo_extended_0.63.1_Linux-64bit.deb"
      # TODO: verify checksum
      - dpkg -i "./hugo.deb"
      - rm -f "./hugo.deb"
      - make build
      - cp -R ./public /output-target/
    volumes:
      - name: website-build-root
        path: /output-target

trigger:
  branch:
    - master
  event:
    - push
    - rollback

volumes:
  - name: website-build-root
    host:
      path: /var/www/gtf.io
