language: go

go:
  - master

install:
  - go get -tags extended github.com/gohugoio/hugo

script:
  - hugo

deploy:
  provider: s3
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  skip_cleanup: true
  local_dir: public
  region: $AWS_REGION
