baseURL: "https://www.gtf.io"
languageCode: "en-gb"
title: "[GTF]"
theme: "gtf.io"
sectionPagesMenu: "main"
params:
  repo: "https://github.com/gfarrell/gtf.io"
  description: "Gideon's small corner of the internet"
