baseURL: "https://www.gtf.io"
languageCode: "en-gb"
title: "[GTF]"
theme: "gtf.io"
sectionPagesMenu: "main"
params:
  repo: "https://github.com/gfarrell/gtf.io"
  description: "Personal website of Gideon Farrell. Contains thoughts, projects, and other things."
ignoreFiles:
  - "/data/"
  - "_notes.md"
  - "_notes/*"
markup:
  highlight:
    codefences: true
    style: lovelace
