baseURL: "https://www.gtf.io"
languageCode: "en-gb"
title: "Gideon's corner of Internet"
theme: "gtf.io"
sectionPagesMenu: "main"
enableGitInfo: true
buildDrafts: true
params:
  repo: "https://github.com/gfarrell/gtf.io"
ignoreFiles:
  - data/*
  - _notes.md
  - _notes/*
markup:
  highlight:
    codefences: true
    style: lovelace
