name = "gtf.io"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "Theme for the gtf.io website"
homepage = "https://gtf.io"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Gideon Farrel"
  homepage = "https://gtf.io"
